version: "3"
services:
  neo4j:
    image: neo4j
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 10s
      timeout: 2s
      retries: 3
    networks:
      - mynet
    volumes:
      - ./db/dbms:/data/couchsurfing
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: on-failure
    depends_on:
      neo4j:
        condition: service_healthy
    networks:
      - mynet
networks:
  mynet:
    driver: bridge
volumes:
  neo4j:
    driver: local
